version: 2.1
orbs:
  node: circleci/node@5.2.0

default_executor: &default_executor
  executor:
    name: node/default
    tag: '20.13.0'

commands:
  install-dependencies:
    parameters:
      cache-version:
        type: string
        default: v1.1
        description: Change the cache version if you need to clear the cache for any reason.

    steps:
      - node/install-yarn:
          version: 1.22.10

      - restore_cache:
          keys:
            - node-deps-<<parameters.cache-version>>-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - node-deps-<<parameters.cache-version>>-{{ checksum "package.json" }}
            - node-deps-<<parameters.cache-version>>

      - run:
          name: yarn install
          command: |
            CKSUM_BEFORE=$(cksum yarn.lock)
            yarn install
            CKSUM_AFTER=$(cksum yarn.lock)

            if [[ $CKSUM_BEFORE != $CKSUM_AFTER ]]; then
              echo "yarn.lock was modified unexpectedly - terminating"
              exit 1
            fi

      - save_cache:
          key: node-deps-<<parameters.cache-version>>-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - packages/eslint-config/node_modules
            - packages/eslint-plugin/node_modules

jobs:
  test:
    <<: *default_executor
    steps:
      - checkout
      - install-dependencies
      - run: yarn run test
      - run: yarn eslint-config-prettier packages/eslint-config/index.js

  test-no-lockfile:
    <<: *default_executor
    steps:
      - checkout
      - node/install-yarn:
          version: 1.22.22
      - run: rm yarn.lock
      - run: yarn install
      - run: yarn run test
      - run: yarn eslint-config-prettier packages/eslint-config/index.js

  lint:
    <<: *default_executor
    steps:
      - checkout
      - install-dependencies
      - run: yarn run lint

workflows:
  version: 2
  ci-checks:
    jobs:
      - test
      - lint

  rules-check:
    triggers:
      - schedule:
          cron: '0 0 * * 1'
          filters:
            branches:
              only:
                - master
    jobs:
      - test-no-lockfile
